apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  ports:
  - port: {{ .Values.app.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.app.servicePort }}
  selector:
    app: vproapp
  type: ClusterIP
