#SPDX-License-Identifier: MIT-0
---
# handlers file for post-install
- name: restarted ntp on Centos 
  service:
   name: chrony
   state: restarted
   enabled: yes
  when: ansible_distribution == "Centos"
- name: restarted ntp on Ubuntu 
  service:
   name: ntp
   state: restarted
   enabled: yes
  when: ansible_distribution == "Ubuntu"
