pipeline {
    agent {
      label 'node1'
    }
    environment {
        appUser = "shoeshop"
        appName = "shoe-ShopingCart"
        appVersion = "0.0.1-SNAPSHOT"
        appType = "jar"
        folderDeploy = "/datas/${appUser}"
        processName = "${appName}-${appVersion}.${appType}"
        buildScript = "mvn clean install -Dskiptest"
        copyScript = "sudo cp target/${processName} ${folderDeploy}"
        perScript = "sudo chown -R ${appUser}:${appUser} ${folderDeploy}"
        killScript = "sudo kill -9 \$(ps -ef| grep ${processName}| grep -v grep| awk '{print \$2}')"
        runScript = 'sudo su ${appUser} -c "cd ${folderDeploy}; java -jar ${processName} > nohup.out 2>&1 &"'

    }
    stages {
        stage('info') {
            steps {
                sh(script: """ whoami;pwd;ls -la;sudo mkdir -p ${folderDeploy} """, label: "firt stage")
            }
        }
        stage('CODE ANALYSIS with SONARQUBE') {
          
		  environment {
             scannerHome = tool 'sonarscanner4'
          }

          steps {
            withSonarQubeEnv('sonar-pro') {
               sh '''${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=vprofile \
                   -Dsonar.projectName=vprofile-repo \
                   -Dsonar.projectVersion=1.0 \
                   -Dsonar.sources=src/ \
                   -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
                   -Dsonar.junit.reportsPath=target/surefire-reports/ \
                   -Dsonar.jacoco.reportsPath=target/jacoco.exec \
                   -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml'''
            }

            timeout(time: 10, unit: 'MINUTES') {
               waitForQualityGate abortPipeline: true
            }
          }
        }
        stage('build'){
            steps{
                sh(script: """ ${buildScript} """, label: "build with maven")
            }
        }
        stage('Deploy'){
            steps{
                sh(script: """ ${copyScript} """, label: "copy the .jar into deploy folder")
                sh(script: """ ${perScript} """, label: "set permission folder")
                sh(script: """ ${killScript} """, label: "terminate the running process")
                sh(script: """ ${runScript} """, label: "run the project")

            }
        }
    }

}
/* #adduser shoeshop
# User privilege specification
root    ALL=(ALL:ALL) ALL
jenkins ALL=(ALL) NOPASSWD: /bin/cp*
jenkins ALL=(ALL) NOPASSWD: /usr/bin/mkdir*
jenkins ALL=(ALL) NOPASSWD: /bin/kill*
jenkins ALL=(ALL) NOPASSWD: /bin/chown*
jenkins ALL=(ALL) NOPASSWD: /bin/su shoeshop* */